# Generated by Django 2.2.6 on 2019-10-30 17:54

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(upload_to='article/avatar/%Y%m%d'),
        ),
    ]
